#!/bin/bash

middleman build
cd ../../

rm -Rf public/*
rm -Rf src/pairing_matrix/templates/*
cp -R assets/generator/build/* public

template_dir=src/pairing_matrix/templates
static_dirs=('images' 'javascripts' 'stylesheets')

mv public/*.html $template_dir
mv public/pairing-matrix/partials public/partials
for dir in public/*/
do
  if ! [[
        ("$dir" == *images*) ||
        ("$dir" == *javascripts*) ||
        ("$dir" == *stylesheets*) ||
        ("$dir" == *fonts*) ||
        ("$dir" == *partials*)]];
    then
    mv $dir $template_dir;
  fi
done
